[package]
name = "bezier-surfaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
log = "0.4"
env_logger = "0.10"

# Math crates
ndarray = "0.15"

